logtracing: export span data
theplant/appkit pull request #66
Opened 2022-08-17 03:59 UTC by w11th

- Replace (*span).AdjustStartTime with WithStartTime
- Add ability to export span data

2022-11-22 02:41 UTC, w11th commented
@bodhi I'm trying to add a feature to export span data. With this, we can use `logtracing` + `Honeycomb exporter` in CFs. It's also a preparation for remote tracing.

Could you please review it when possible?

2022-11-25 00:37 UTC, bodhi requested changes
@w11th can you please update the README for log tracing to show
1. How to set this up (vs using the standard logging output)
2. What (if anything) changes on the client side when using this exporter vs the logging exporter.

Also, at what point should we switch to OTEL, with our own exporter?

2022-11-25 06:22 UTC, w11th commented
Thanks, @bodhi. I have updated the README to add a paragraph "Export span data": [9a30936](https://github.com/theplant/appkit/pull/66/commits/9a309369d3659a19c4d00c6e345ed6954498b666)

2022-11-25 06:44 UTC, w11th commented
> Also, at what point should we switch to OTEL, with our own exporter?

@bodhi I think we can start the switch now. I can start with `mcd-ketchup`.

OTEL is well-known and full-featured. If we decide to switch to OTEL, it seems unnecessary to keep adding features (remote tracing/adding events...) to `logtracing`. 
(Jaden and I talked about this a while ago, before this [PR](https://github.com/theplant/appkit/pull/68).)

2022-11-27 23:42 UTC, bodhi approved these changes
Thanks @w11th

2022-11-27 23:42 UTC, bodhi commented on logtracing/README.md
> +    logtracing.RegisterExporter(expoter)
```suggestion
    logtracing.RegisterExporter(exporter)
```

2022-11-27 23:42 UTC, bodhi commented on logtracing/README.md
> +When you register exporters, `logtracing` will pass sampled spans to the exporters after logging.
Ah, so this will log *and* export to Honeycomb? I thought it was a replacement!

2022-11-27 23:43 UTC, bodhi commented
> I think we can start the switch now. I can start with mcd-ketchup.

Can you do a PR on a single component, so we can see the difference?

2022-11-28 02:39 UTC, w11th commented
> Can you do a PR on a single component, so we can see the difference?

YES, I will do that. https://theplanttokyo.atlassian.net/browse/MKP-249

2022-11-28 02:51 UTC, merged